# Form implementation generated from reading ui file 'ui\Windows\StarLight_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1536, 864)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("/* Глобальные настройки */\n"
"QWidget {\n"
"    background-color: rgba(30, 34, 45, 255);\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"    color: #D8DEE9;\n"
"}\n"
"\n"
"/* Глобальные настройки */\n"
"QFrame {\n"
"     background-color: #2E3440;\n"
"    border-radius: 5px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"    background-color: #3B4252;\n"
"    border: 1px solid rgba(80, 85, 95, 255);\n"
"    color: #D8DEE9;\n"
"    padding:0px;\n"
"    border-radius: 4px;\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #434C5E;\n"
"    border: 1px solid #5E81AC;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2E3440;\n"
"    border: 1px solid #3A7CA5;\n"
"    color: #88C0D0;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 34, 45, 255), stop:1 rgba(20, 24, 35, 255));\n"
"    border: 1px solid rgba(60, 65, 75, 255);\n"
"    color: rgba(100, 100, 100, 255);\n"
"}\n"
"\n"
"QSlider\n"
"{\n"
"     background-color: #2E3440;\n"
"}\n"
"\n"
"/* Слайдеры (без изменений) */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #4C566A;\n"
"    height: 6px;\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #3B4252, stop:1 #2E3440\n"
"    );\n"
"    border-radius: 3px;\n"
"    margin: 0 12px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #5E81AC, stop:0.5 #81A1C1, stop:1 #3A7CA5\n"
"    );\n"
"    border: 1px solid #3A7CA5;\n"
"    width: 20px;\n"
"    height: 28px;\n"
"    margin: -11px 0;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-left-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    position: relative;\n"
"}\n"
"QSlider::handle:horizontal::before {\n"
"    content: \"\";\n"
"    position: absolute;\n"
"    top: -4px;\n"
"    left: 0px;\n"
"    width: 12px;\n"
"    height: 8px;\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #81A1C1, stop:1 #5E81AC\n"
"    );\n"
"    border: 1px solid #3A7CA5;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    box-shadow: 0 2px 4px rgba(0,0,0,0.4);\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #88C0D0, stop:0.5 #A3B8D1, stop:1 #5E81AC\n"
"    );\n"
"    border: 1px solid #81A1C1;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #A3B8D1, stop:0.5 #88C0D0, stop:1 #81A1C1\n"
"    );\n"
"    border: 1px solid #88C0D0;\n"
"}\n"
"\n"
"/* Текст */\n"
"QLabel {\n"
"    color: #D8DEE9;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    font-weight: normal;\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"/* Другие текстовые элементы */\n"
"QLineEdit, QComboBox, QTextEdit, QSpinBox, QMenuBar, QMenu {\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"    color: #D8DEE9;\n"
"}\n"
"\n"
"/* Чекбокс */\n"
"QCheckBox {\n"
"    spacing: 6px;\n"
"    color: #D8DEE9;\n"
"    background-color:  rgba(0, 0, 0, 0);\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 4px;\n"
"    border: 1.5px solid rgba(80, 85, 95, 255);\n"
"    background-color: #3B4252;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #5E81AC;\n"
"    background-color: #434C5E;\n"
"}\n"
"\n"
"QCheckBox::indicator:pressed {\n"
"    background-color: #2E3440;\n"
"    border-color: #3A7CA5;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #5E81AC;\n"
"    border: 1.5px solid #81A1C1;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #81A1C1;\n"
"    border-color: #A3B8D1;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"    background-color: #88C0D0;\n"
"    border-color: #5E81AC;\n"
"}\n"
"")
        self.StarLight_window = QtWidgets.QWidget(parent=MainWindow)
        self.StarLight_window.setStyleSheet("/* ===== ТЁМНАЯ ТЕМА (СЕРЫЙ + СИНИЙ) ===== */\n"
"/* Глобальные настройки */\n"
"QWidget {\n"
"    background-color: #1d1d1d;\n"
"}\n"
"\n"
"QStackedWidget {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"\n"
"/* Фреймы */\n"
"QFrame {\n"
"    background-color: #303030; /* Фон фреймов */\n"
"    border-radius: 5px;\n"
"    padding: 0px;\n"
"    border: 0px solid #353535; /* Граница фреймов */\n"
"}\n"
"\n"
"/* Основные кнопки */\n"
"QPushButton {\n"
"    background-color: #545454; /* Стандартный серый */\n"
"    border: 1px solid #353535;\n"
"    color: #ffffff;\n"
"    border-radius: 4px;\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #6c7d9d; /* Светло-синяя граница */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #303030; /* Темнее при нажатии */\n"
"    border: 1px solid #4d6490; /* Тёмно-синий */\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #1d1d1d;\n"
"    border: 1px solid #4d6490; /* Синий для выделенных */\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #242424;\n"
"    border: 1px solid #353535;\n"
"    color: #797979; /* Серый текст */\n"
"}\n"
"\n"
"/* Текст */\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    font-weight: normal;\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #797979; /* Серый для неактивных */\n"
"}\n"
"\n"
"/* Поля ввода */\n"
"QLineEdit {\n"
"    background-color: #545454;\n"
"    border: 1px solid #353535;\n"
"    color: #ffffff;\n"
"    padding: 0px 8px;\n"
"    border-radius: 4px;\n"
"    selection-background-color: #4d6490; /* Синий для выделения текста */\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 1px solid #6c7d9d; /* Светло-синяя граница */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #6c7d9d; /* Светло-синий при фокусе */\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #242424;\n"
"    border: 1px solid #353535;\n"
"    color: #797979;\n"
"}\n"
"\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #303030;\n"
"    color: #cccccc;\n"
"}\n"
"\n"
"\n"
"/* Чекбоксы */\n"
"QCheckBox {\n"
"    spacing: 6px;\n"
"    color: #ffffff;\n"
"    background-color: transparent;\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QCheckBox:disabled {\n"
"    color: #797979;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 3px;\n"
"    border: 1.5px solid #545454;\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #6c7d9d; /* Синий при наведении */\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #4d6490; /* Синий фон */\n"
"    border: 1.5px solid #6c7d9d; /* Светло-синяя граница */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #6c7d9d; /* Светлее синий */\n"
"    border-color: #8a9bb9;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: #242424;\n"
"    border: 1.5px solid #353535;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled {\n"
"    background-color: #3a4a6b; /* Тёмно-синий */\n"
"    border: 1.5px solid #353535;\n"
"}\n"
"\n"
"/* Группбоксы */\n"
"QGroupBox {\n"
"    border: 1px solid #353535;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"    padding-top: 10px;\n"
"    background-color: #3d3d3d;\n"
"    color: #ffffff;\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0px 8px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Прогресс-бар */\n"
"QProgressBar {\n"
"    background-color: #303030;\n"
"    border: 1px solid #353535;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: #ffffff;\n"
"    font-family: \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QProgressBar:disabled {\n"
"    color: #797979;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #4d6490, stop:1 #6c7d9d  /* Синий градиент */\n"
"    );\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"    background: #545454; /* Серый для неактивных */\n"
"}\n"
"\n"
"/* Слайдеры */\n"
"QSlider {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Горизонтальные слайдеры */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #353535;\n"
"    height: 6px;\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #303030, stop:1 #1d1d1d\n"
"    );\n"
"    border-radius: 3px;\n"
"    margin: 0 6px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:disabled {\n"
"    border: 1px solid #353535;\n"
"    background: #242424;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #6c7d9d; /* Синий ползунок */\n"
"    border: 1px solid #8a9bb9;\n"
"    width: 8px;\n"
"    height: 14px;\n"
"    margin: -6px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #8a9bb9; /* Светло-синий при наведении */\n"
"    border: 1px solid #a8b9d6;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"    background: #545454;\n"
"    border: 1px solid #353535;\n"
"}\n"
"\n"
"/* Вертикальные слайдеры */\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #353535;\n"
"    width: 6px;\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #303030, stop:1 #1d1d1d\n"
"    );\n"
"    border-radius: 3px;\n"
"    margin: 6px 0;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: #6c7d9d;\n"
"    border: 1px solid #8a9bb9;\n"
"    width: 14px;\n"
"    height: 8px;\n"
"    margin: 0 -6px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"    background: #8a9bb9;\n"
"    border: 1px solid #a8b9d6;\n"
"}\n"
"\n"
"/* Спинбоксы */\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color: #303030;\n"
"    border: 1px solid #353535;\n"
"    color: #ffffff;\n"
"    padding: 2px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSpinBox:hover, QDoubleSpinBox:hover {\n"
"    border: 1px solid #545454; /* Светло-серая граница */\n"
"}\n"
"\n"
"QSpinBox:focus, QDoubleSpinBox:focus {\n"
"    border: 1px solid #6c7d9d; /* Светло-синий при фокусе */\n"
"}\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button,\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button {\n"
"    border: 1px solid #353535;\n"
"    background-color: #353535;\n"
"    width: 16px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover,\n"
"QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover {\n"
"    background-color: #3d3d3d;\n"
"    border: 1px solid #545454;\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {\n"
"    border-left: 3px solid transparent;\n"
"    border-right: 3px solid transparent;\n"
"    border-bottom: 6px solid #ffffff;\n"
"}\n"
"\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {\n"
"    border-left: 3px solid transparent;\n"
"    border-right: 3px solid transparent;\n"
"    border-top: 6px solid #ffffff;\n"
"}\n"
"\n"
"/* Меню */\n"
"QMenuBar {\n"
"    background-color: #1d1d1d;\n"
"    color: #ffffff;\n"
"    border-bottom: 1px solid #353535;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 5px 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #353535;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background-color: #4d6490; /* Синий при нажатии */\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #303030;\n"
"    color: #ffffff;\n"
"    border: 1px solid #353535;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 5px 20px 5px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #4d6490; /* Синий фон выбора */\n"
"}\n"
"\n"
"QMenu::item:disabled {\n"
"    color: #797979;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #353535;\n"
"    margin: 5px 10px;\n"
"}\n"
"\n"
"/* Таблицы */\n"
"QTableView, QTableWidget {\n"
"    background-color: #303030;\n"
"    color: #ffffff;\n"
"    border: 1px solid #353535;\n"
"    gridline-color: #353535;\n"
"    alternate-background-color: #2b2b2b;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #353535;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"    border: 1px solid #545454;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background-color: #3d3d3d;\n"
"}\n"
"\n"
"QTableView::item:selected, QTableWidget::item:selected {\n"
"    background-color: #4d6490; /* Синий фон выделения */\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QTableView::item:focus, QTableWidget::item:focus {\n"
"    background-color: #6c7d9d; /* Светло-синий при фокусе */\n"
"    border: 1px solid #8a9bb9;\n"
"}\n"
"\n"
"/* Вкладки */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #353535;\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #353535;\n"
"    color: #ffffff;\n"
"    padding: 6px 12px;\n"
"    margin-right: 2px;\n"
"    border: 1px solid #545454;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #3d3d3d;\n"
"    border-color: #545454;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #303030;\n"
"    border-color: #6c7d9d; /* Синяя граница для активной вкладки */\n"
"    border-bottom-color: #303030; /* Сливаем с фоном */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* Немного поднимаем неактивные вкладки */\n"
"}\n"
"\n"
"/* Скроллбары */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: #303030;\n"
"    border: 1px solid #353535;\n"
"    border-radius: 3px;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: #353535;\n"
"    border-radius: 5px;\n"
"    min-height: 20px;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {\n"
"    background-color: #3d3d3d;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed, QScrollBar::handle:horizontal:pressed {\n"
"    background-color: #4d6490; /* Синий при нажатии */\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background-color: #303030;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background-color: #303030;\n"
"}")
        self.StarLight_window.setObjectName("StarLight_window")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.StarLight_window)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.BG_9 = QtWidgets.QFrame(parent=self.StarLight_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BG_9.sizePolicy().hasHeightForWidth())
        self.BG_9.setSizePolicy(sizePolicy)
        self.BG_9.setMaximumSize(QtCore.QSize(200, 177))
        self.BG_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BG_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BG_9.setObjectName("BG_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.BG_9)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Temperature_spin_box = QtWidgets.QDoubleSpinBox(parent=self.BG_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temperature_spin_box.sizePolicy().hasHeightForWidth())
        self.Temperature_spin_box.setSizePolicy(sizePolicy)
        self.Temperature_spin_box.setMinimumSize(QtCore.QSize(74, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Temperature_spin_box.setFont(font)
        self.Temperature_spin_box.setStyleSheet("")
        self.Temperature_spin_box.setObjectName("Temperature_spin_box")
        self.gridLayout_3.addWidget(self.Temperature_spin_box, 2, 0, 1, 2)
        self.Current_temp_label = QtWidgets.QLineEdit(parent=self.BG_9)
        self.Current_temp_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Current_temp_label.sizePolicy().hasHeightForWidth())
        self.Current_temp_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.Current_temp_label.setFont(font)
        self.Current_temp_label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.Current_temp_label.setMouseTracking(False)
        self.Current_temp_label.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Current_temp_label.setToolTipDuration(0)
        self.Current_temp_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Current_temp_label.setStyleSheet("QLineEdit {\n"
"    background-color:  rgba(80, 85, 95, 0);\n"
"    border: 1px solid rgba(80, 85, 95, 0);\n"
"    color: rgba(220, 220, 220, 255);\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.Current_temp_label.setCursorPosition(8)
        self.Current_temp_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Current_temp_label.setReadOnly(True)
        self.Current_temp_label.setObjectName("Current_temp_label")
        self.gridLayout_3.addWidget(self.Current_temp_label, 4, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(parent=self.BG_9)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("")
        self.label_38.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 0, 0, 1, 2)
        self.label_40 = QtWidgets.QLabel(parent=self.BG_9)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("")
        self.label_40.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_40.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 2)
        self.Fan_checkBox = QtWidgets.QCheckBox(parent=self.BG_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fan_checkBox.sizePolicy().hasHeightForWidth())
        self.Fan_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Fan_checkBox.setFont(font)
        self.Fan_checkBox.setStyleSheet("")
        self.Fan_checkBox.setObjectName("Fan_checkBox")
        self.gridLayout_3.addWidget(self.Fan_checkBox, 6, 0, 1, 2)
        self.Cooling_checkBox = QtWidgets.QCheckBox(parent=self.BG_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cooling_checkBox.sizePolicy().hasHeightForWidth())
        self.Cooling_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Cooling_checkBox.setFont(font)
        self.Cooling_checkBox.setStyleSheet("")
        self.Cooling_checkBox.setObjectName("Cooling_checkBox")
        self.gridLayout_3.addWidget(self.Cooling_checkBox, 5, 0, 1, 2)
        self.gridLayout.addWidget(self.BG_9, 1, 0, 1, 1)
        self.BG_10 = QtWidgets.QFrame(parent=self.StarLight_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BG_10.sizePolicy().hasHeightForWidth())
        self.BG_10.setSizePolicy(sizePolicy)
        self.BG_10.setMaximumSize(QtCore.QSize(500, 177))
        self.BG_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.BG_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.BG_10.setObjectName("BG_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.BG_10)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.start_exposure = QtWidgets.QPushButton(parent=self.BG_10)
        self.start_exposure.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.start_exposure.setFont(font)
        self.start_exposure.setStyleSheet("")
        self.start_exposure.setObjectName("start_exposure")
        self.gridLayout_2.addWidget(self.start_exposure, 10, 1, 1, 2)
        self.label_48 = QtWidgets.QLabel(parent=self.BG_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("")
        self.label_48.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 8, 3, 1, 2)
        self.exp_bin_y = QtWidgets.QLineEdit(parent=self.BG_10)
        self.exp_bin_y.setMinimumSize(QtCore.QSize(0, 25))
        self.exp_bin_y.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.exp_bin_y.setFont(font)
        self.exp_bin_y.setStyleSheet("    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius:4px;")
        self.exp_bin_y.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exp_bin_y.setObjectName("exp_bin_y")
        self.gridLayout_2.addWidget(self.exp_bin_y, 7, 3, 1, 2)
        self.label_44 = QtWidgets.QLabel(parent=self.BG_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("")
        self.label_44.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 8, 1, 1, 1)
        self.exp_height = QtWidgets.QLineEdit(parent=self.BG_10)
        self.exp_height.setMinimumSize(QtCore.QSize(0, 25))
        self.exp_height.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.exp_height.setFont(font)
        self.exp_height.setStyleSheet("    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius:4px;")
        self.exp_height.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exp_height.setObjectName("exp_height")
        self.gridLayout_2.addWidget(self.exp_height, 7, 2, 1, 1)
        self.StarLight_progressBar = QtWidgets.QProgressBar(parent=self.BG_10)
        self.StarLight_progressBar.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.StarLight_progressBar.setFont(font)
        self.StarLight_progressBar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.StarLight_progressBar.setStyleSheet("/* --- Progress Bar --- */\n"
"QProgressBar {\n"
"    background-color: #3B4252;    /* Цвет фона */\n"
"    border: 1px solid #4C566A;    /* Граница */\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: #E5E9F0;               /* Цвет текста */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3A7CA5, stop:1 #4F9CD6\n"
"    );\n"
"}")
        self.StarLight_progressBar.setProperty("value", 100)
        self.StarLight_progressBar.setObjectName("StarLight_progressBar")
        self.gridLayout_2.addWidget(self.StarLight_progressBar, 10, 3, 1, 3)
        self.label_43 = QtWidgets.QLabel(parent=self.BG_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("")
        self.label_43.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 8, 2, 1, 1)
        self.exp_y0 = QtWidgets.QLineEdit(parent=self.BG_10)
        self.exp_y0.setMinimumSize(QtCore.QSize(0, 25))
        self.exp_y0.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.exp_y0.setFont(font)
        self.exp_y0.setStyleSheet("    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius:4px;\n"
"")
        self.exp_y0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exp_y0.setObjectName("exp_y0")
        self.gridLayout_2.addWidget(self.exp_y0, 7, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(parent=self.BG_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("")
        self.label_50.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_50.setWordWrap(False)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 4, 5, 1, 1)
        self.exp_time = QtWidgets.QLineEdit(parent=self.BG_10)
        self.exp_time.setMinimumSize(QtCore.QSize(0, 25))
        self.exp_time.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.exp_time.setFont(font)
        self.exp_time.setStyleSheet("    border-radius: 4px;")
        self.exp_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exp_time.setObjectName("exp_time")
        self.gridLayout_2.addWidget(self.exp_time, 6, 5, 1, 1)
        self.exp_x0 = QtWidgets.QLineEdit(parent=self.BG_10)
        self.exp_x0.setMinimumSize(QtCore.QSize(0, 25))
        self.exp_x0.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.exp_x0.setFont(font)
        self.exp_x0.setStyleSheet("    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;")
        self.exp_x0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exp_x0.setObjectName("exp_x0")
        self.gridLayout_2.addWidget(self.exp_x0, 6, 1, 1, 1)
        self.exp_width = QtWidgets.QLineEdit(parent=self.BG_10)
        self.exp_width.setMinimumSize(QtCore.QSize(0, 25))
        self.exp_width.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.exp_width.setFont(font)
        self.exp_width.setStyleSheet("    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;")
        self.exp_width.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exp_width.setObjectName("exp_width")
        self.gridLayout_2.addWidget(self.exp_width, 6, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(parent=self.BG_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("")
        self.label_45.setScaledContents(True)
        self.label_45.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_45.setWordWrap(False)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 4, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(parent=self.BG_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("")
        self.label_42.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 4, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(parent=self.BG_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("")
        self.label_49.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 4, 3, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 9, 1, 1, 5)
        self.exp_bin_x = QtWidgets.QLineEdit(parent=self.BG_10)
        self.exp_bin_x.setMinimumSize(QtCore.QSize(0, 25))
        self.exp_bin_x.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.exp_bin_x.setFont(font)
        self.exp_bin_x.setStyleSheet("    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;")
        self.exp_bin_x.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.exp_bin_x.setObjectName("exp_bin_x")
        self.gridLayout_2.addWidget(self.exp_bin_x, 6, 3, 1, 2)
        self.label_41 = QtWidgets.QLabel(parent=self.BG_10)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("")
        self.label_41.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 0, 0, 3, 6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 5)
        self.progressBar_label = QtWidgets.QLabel(parent=self.BG_10)
        self.progressBar_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.progressBar_label.setText("")
        self.progressBar_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.progressBar_label.setObjectName("progressBar_label")
        self.gridLayout_2.addWidget(self.progressBar_label, 8, 5, 1, 1)
        self.gridLayout.addWidget(self.BG_10, 1, 1, 1, 1)
        self.Main_Image = QtWidgets.QLabel(parent=self.StarLight_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_Image.sizePolicy().hasHeightForWidth())
        self.Main_Image.setSizePolicy(sizePolicy)
        self.Main_Image.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Main_Image.setFont(font)
        self.Main_Image.setStyleSheet("")
        self.Main_Image.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.Main_Image.setText("")
        self.Main_Image.setObjectName("Main_Image")
        self.gridLayout.addWidget(self.Main_Image, 0, 3, 2, 1)
        self.frame = QtWidgets.QFrame(parent=self.StarLight_window)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.StarLight_window)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Current_temp_label.setText(_translate("MainWindow", "-12.3 °C"))
        self.label_38.setText(_translate("MainWindow", "Охлаждение камеры"))
        self.label_40.setText(_translate("MainWindow", "Температура"))
        self.Fan_checkBox.setText(_translate("MainWindow", "Вентилятор"))
        self.Cooling_checkBox.setText(_translate("MainWindow", "Охлаждение"))
        self.start_exposure.setText(_translate("MainWindow", "Начать экспозицию"))
        self.label_48.setText(_translate("MainWindow", "Биннинг Y"))
        self.exp_bin_y.setText(_translate("MainWindow", "2"))
        self.label_44.setText(_translate("MainWindow", "Смещение Y"))
        self.exp_height.setText(_translate("MainWindow", "2712"))
        self.label_43.setText(_translate("MainWindow", "Высота"))
        self.exp_y0.setText(_translate("MainWindow", "0"))
        self.label_50.setText(_translate("MainWindow", "Время экспозиции"))
        self.exp_time.setText(_translate("MainWindow", "1000"))
        self.exp_x0.setText(_translate("MainWindow", "0"))
        self.exp_width.setText(_translate("MainWindow", "3388"))
        self.label_45.setText(_translate("MainWindow", "Смещение X"))
        self.label_42.setText(_translate("MainWindow", "Ширина"))
        self.label_49.setText(_translate("MainWindow", "Биннинг X"))
        self.exp_bin_x.setText(_translate("MainWindow", "2"))
        self.label_41.setText(_translate("MainWindow", "Экспозиция изображения"))
