# Form implementation generated from reading ui file 'ui\ControllerSettings\command_builder\CommandBuilder.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_commands_GroupBox(object):
    def setupUi(self, commands_GroupBox):
        commands_GroupBox.setObjectName("commands_GroupBox")
        commands_GroupBox.resize(622, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(commands_GroupBox.sizePolicy().hasHeightForWidth())
        commands_GroupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        commands_GroupBox.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(commands_GroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.commands_comboBox = QtWidgets.QComboBox(parent=commands_GroupBox)
        self.commands_comboBox.setObjectName("commands_comboBox")
        self.gridLayout.addWidget(self.commands_comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.coder_groupBox = QtWidgets.QGroupBox(parent=commands_GroupBox)
        self.coder_groupBox.setObjectName("coder_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.coder_groupBox)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.coder_format_comboBox = QtWidgets.QComboBox(parent=self.coder_groupBox)
        self.coder_format_comboBox.setObjectName("coder_format_comboBox")
        self.gridLayout_3.addWidget(self.coder_format_comboBox, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.coder_stackedWidget = QtWidgets.QStackedWidget(parent=self.coder_groupBox)
        self.coder_stackedWidget.setObjectName("coder_stackedWidget")
        self.gridLayout_3.addWidget(self.coder_stackedWidget, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.coder_groupBox, 1, 0, 1, 1)
        self.decoder_groupBox = QtWidgets.QGroupBox(parent=commands_GroupBox)
        self.decoder_groupBox.setObjectName("decoder_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.decoder_groupBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.decoder_format_comboBox = QtWidgets.QComboBox(parent=self.decoder_groupBox)
        self.decoder_format_comboBox.setObjectName("decoder_format_comboBox")
        self.gridLayout_2.addWidget(self.decoder_format_comboBox, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.decoder_stackedWidget = QtWidgets.QStackedWidget(parent=self.decoder_groupBox)
        self.decoder_stackedWidget.setObjectName("decoder_stackedWidget")
        self.gridLayout_2.addWidget(self.decoder_stackedWidget, 2, 0, 1, 3)
        self.gridLayout.addWidget(self.decoder_groupBox, 3, 0, 1, 1)

        self.retranslateUi(commands_GroupBox)
        QtCore.QMetaObject.connectSlotsByName(commands_GroupBox)

    def retranslateUi(self, commands_GroupBox):
        _translate = QtCore.QCoreApplication.translate
        commands_GroupBox.setWindowTitle(_translate("commands_GroupBox", "GroupBox"))
        commands_GroupBox.setTitle(_translate("commands_GroupBox", "Команды устройства"))
        self.coder_groupBox.setTitle(_translate("commands_GroupBox", "Сборка команды"))
        self.decoder_groupBox.setTitle(_translate("commands_GroupBox", "Интерпретация команды"))
