# Form implementation generated from reading ui file 'ui\ControllerSettings\DeviceConnectionSettings.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(487, 191)
        self.gridLayout_2 = QtWidgets.QGridLayout(GroupBox)
        self.gridLayout_2.setContentsMargins(9, 9, 6, 6)
        self.gridLayout_2.setSpacing(9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.profile_status_label = QtWidgets.QLabel(parent=GroupBox)
        self.profile_status_label.setText("")
        self.profile_status_label.setObjectName("profile_status_label")
        self.gridLayout.addWidget(self.profile_status_label, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=GroupBox)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.profile_list_comboBox = QtWidgets.QComboBox(parent=GroupBox)
        self.profile_list_comboBox.setObjectName("profile_list_comboBox")
        self.gridLayout.addWidget(self.profile_list_comboBox, 1, 2, 1, 1)
        self.ECHO_period_doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=GroupBox)
        self.ECHO_period_doubleSpinBox.setDecimals(1)
        self.ECHO_period_doubleSpinBox.setMinimum(0.1)
        self.ECHO_period_doubleSpinBox.setSingleStep(0.1)
        self.ECHO_period_doubleSpinBox.setObjectName("ECHO_period_doubleSpinBox")
        self.gridLayout.addWidget(self.ECHO_period_doubleSpinBox, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=GroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=GroupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=GroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=GroupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 2)
        self.use_ECHO_checkBox = QtWidgets.QCheckBox(parent=GroupBox)
        self.use_ECHO_checkBox.setObjectName("use_ECHO_checkBox")
        self.gridLayout.addWidget(self.use_ECHO_checkBox, 4, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        GroupBox.setTitle(_translate("GroupBox", "Интерфейс"))
        self.label.setText(_translate("GroupBox", "Профиль: "))
        self.ECHO_period_doubleSpinBox.setSuffix(_translate("GroupBox", " сек "))
        self.label_3.setText(_translate("GroupBox", "Подключение:"))
        self.label_2.setText(_translate("GroupBox", "Статус:"))
        self.label_4.setText(_translate("GroupBox", "Настройки:"))
        self.label_5.setText(_translate("GroupBox", "Интервал опроса ЭХО:"))
        self.use_ECHO_checkBox.setText(_translate("GroupBox", "Использовать ЭХО команду"))
